<?php

	$routes = [
		'default' => 'index/books',
		'view_book' => 'view/books',
		'view_errors' => 'view/errors',
		'view_author' => 'view/authors',
		'ad_author' => 'ad/authors',
		'view_category' => 'view/categories',
		'ad_category' => 'ad/categories',
		'view_edition' => 'view/editions',
		'ad_edition' => 'ad/editions',
		'view_library' => 'view/libraries',
		'ad_library' => 'ad/libraries',
		'view_admin' => 'admin/pages',
		'setAdmin_users' => 'setAdmin/users',
		'setUser_users' => 'setUser/users',
		'delete_users' => 'delete/users',
		'view_user' => 'view/users',
		'ad_users' => 'ad/users',
		'view_result' => 'search/pages',
		'index_categories' => 'index/categories',
		'index_authors' => 'index/authors',
		'index_libraries' => 'index/libraries',
		'index_editions' => 'index/editions',
		'index_disponibilities' => 'index/disponibilities',
		'login_users' => 'login/users',
		'disconnect_users' => 'disconnect/users',
		'check_users' => 'check/users',
		'register_users' => 'register/users',
		'create_users' => 'create/users',
		'create_books' => 'create/books',
		'change_books' => 'change/books',
		'edit_book' => 'edit/books',
		'editImg_book' => 'editImg/books',
		'replaceImg_book' => 'replaceImg/books',
		'delete_books' => 'delete/books',
		'create_authors' => 'create/authors',
		'create_editions' => 'create/editions',
		'create_categories' => 'create/categories',
		'create_libraries' => 'create/libraries',
		'pagination_books' => 'pagination/books',
		'add_favourite' => 'addfave/books',
		'remove_favourite' => 'removefave/books'
		// gauche = fontion et droite = controler.
	];